const data = {
    products: [
      {
        _id: '1',
        name: 'Wings of Fire1',
        category: 'Mystery',
        image: '/images/book1.png',
        price: 121,
        countInStock: 10,
        author: 'XYZ',
        rating: 4.5,
        numReviews: 10,
        description: 'Goood Book!!',
      },
      {
        name: 'Wings of Fire2',
        category: 'Mystery',
        image: '/images/book1.png',
        price: 122,
        countInStock: 0,
        author: 'XYZ',
        rating: 4.5,
        numReviews: 10,
        description: 'Good Book!!',
      },
      {
        name: 'Wings of Fire3',
        category: 'Mystery',
        image: '/images/book1.png',
        price: 120,
        countInStock: 10,
        author: 'XYZ',
        rating: 4.5,
        numReviews: 10,
        description: 'Good Book!',
      },
      {
        name: 'Wings of Fire4',
        category: 'Mystery',
        image: '/images/book1.png',
        price: 120,
        countInStock: 10,
        author: 'XYZ',
        rating: 4.5,
        numReviews: 10,
        description: 'Good Book!',
      },
      {
        name: 'Wings of Fire5',
        category: 'Mystery',
        image: '/images/book1.png',
        price: 320,
        countInStock: 10,
        author: 'XYZ',
        rating: 4.5,
        numReviews: 10,
        description: 'Good Book!!',
      },
      {
        name: 'Malgudi Days',
        category: 'Thriller',
        image: '/images/book2.png',
        price: 200,
        countInStock: 10,
        author: 'R.K Narayan',
        rating: 4.5,
        numReviews: 10,
        description: 'Good Book',
      },
    ],
  };
  export default data;
  